### PR TITLE
Revert "Support for multiple projects with deliverable outputs"

### PR DESCRIPTION
**Pull request by tpetricek**
I think this does not currently work. Has anyone actually tested this?

I tried copying the `generate.fsx` file from Scaffold to F# Formatting and the `findBinaries` function from this PR is broken (see [here](https://github.com/fsprojects/ProjectScaffold/commit/2f1114719c770e0adb4d673c7c8324c09e2dcc43#diff-81ae5407f63d36059f9e8cc989eedb9fR68)). It does not get binaries correctly.

Aside, I think this PR is actually making it really hard to update existing projects with single-project output to a new version of project scaffold, so I'm not sure if merging this is actually such a good idea. (Though I definitely see how this would be useful for some other projects.)

In any case, we should fix the PR before merging this into master.

### CODE REVIEW

**Comment by tpetricek** [comment]
Actually, the best option might be if the `generate.fsx` script supports both scenarios - when you have `dll` files directly in the `bin` folder and when you have them in sub-folders.

**Comment by tpetricek** [comment]
cc @Vidarls

**Comment by tpetricek** [comment]
Also, I think we cannot just blindly run the documentation generator on all `dll` files in the output folder, because the build might copy other 3rd party binaries there - and you do not want to see those in your documentation!

**Comment by Vidarls** [comment]
I'm using this on quite a few projects, and so far I've not had any issues. I'm guessing the issue might be the new expected subfolder structure in the bin folder. (Previuosly all files in `./bin` now expects `./bin/[project name]` )

> __Disclaimer:__ Reverting this forever will require me to maintain my own fork with multiproject support, so I am not really unbiased.

I believe restricting Projectscaffold to single output library projects is severly limiting it, and it also encourages _fat packages_ rather than the _small core_ + _extensions_ that many library projects uses (nancyfx, simple.data comes to mind).

I agree with you that we should probably not be so strict with how we want the binaries to be organized. You idea will probably work. Alternatively we could look at porting the _find_binaries_  part of `paket pack` that parses project files to magically find binaries to include in nuget pakcages.

**Comment by dnauck** [comment]
Looks like this issue is related to #152

**Comment by dnauck** [comment]
I agree with @Vidarls, it's not possible to limit every VS project to output to root/bin. His new solution was very useful and makes Project Scaffold useable for multi project solutions.

It just needs some more love to support the *find_binaries* stuff from paket.

**Comment by tpetricek** [comment]
I'm not necessarily saying we should revert everything forever. But can someone please explain how can the following code:

    let binaries =   
        directoryInfo bin    
        |> subDirectories   
        |> Array.map (fun d -> d.FullName @@ (sprintf "%s.dll" d.Name))   
        |> List.ofArray 

ever work?? This is just looking for directory names and then it appends ".dll" at the end! This might work if you have subdirectories for each DLL but it is not going to work in general.

Can you send a PR that lets user specify the DLL files they want to pass to MetadataFormat (simply as file names) and then finds all of those in the `bin` folder or its sub-directories? (That would work for both of the scenarios).

**Comment by Vidarls** [comment]
It works on conventions, not adhering to the conventions will have the search for binaries fail.

Each project is expected to output a dll to `./bin/projectName/projectName.dll` (any other referenced dll's will still be in the `./bin/projectName` directory, but as you pointed out, we really don't want to create docs for them).

The reasoning behind this solution was that ProjectScaffold can allow itself to be quite opinionated, and if the projects did not change the default behaviour, binaries would be copied from the default Visual studio output path of `./src/projectName/bin/Release` to `./bin/projectName`. 
Given the default naming conventions of newly create Visual Studio projects, this would yield the structure described in the above paragraph. It would provide a nice happy path where the build process did not require specific tweaks when adding extra projects to a solution. I do however understand you annoyance that this change breaks previous projects, using the single bin folder output.

Having the user manually specify the binaries to include is simple enough (basically this is what the previous version did).

The downside is that you have to keep manually updating the generate.fsx file as the solution structure changes (adding / removing projects, renaming projects.) Also it will break any projects created with the current master as base.

That said, structural changes are not that frequent, and it is an easy fix for existing projects, so it might not be worth it to come up with some automated solution to cater for every invariant.

Would a composite solution work for you:

`let binariesToDocument = binariesFromConventions @ manuallySpecifiedBinaries`

this one could probably be made to merge nicely with the old version where you specified the filenames in a list at the top, so the upgrade should be quite smooth.

unfortunately I'm a bit swamped after being away for the easter holidays, so I'm not sure when I have time to put this idea into code.

**Comment by tpetricek** [comment]
I think having `manuallySpecifiedBinaries` would address my problem.

The whole motivation behind this is that I think people who used earlier versions of ProjectScaffold might want to update their project to use the latest version - because it has more functionality - although this is not something that needs to work automatically, we should make it reasonably easy. 

We can make it easy in different ways - I think adding a comment that explains the convention (and suggesting how people can change it) would actually be sufficient. When I was trying to adapt the code so that I can use it in F# Formatting, I was simply *completely* confused by that snippet. And I suspect others modifying it may be equally confused about what it means.

**Comment by dsyme** [comment]
Closing old out of date PR

**Pull request closed without merging**
