### PR TITLE
(fix) htm5shiv moved from googlecode to github.

### PR DESCRIPTION
**Pull request by DmitriyVlasov**
small fix.

### CODE REVIEW

**Comment by DmitriyVlasov** [comment]
Small fix of template.

**Comment by nickbabcock** [comment]
Github doesn't like direct linking. Try replacing the link with a CDN:

    //cdn.jsdelivr.net/html5shiv/3.7.2/html5shiv.min.js

**Comment by forki** [comment]
is it ready to merge?

**Comment by nickbabcock** [comment]
Please don't merge, the suggested change to `https://github.com/aFarkas/html5shiv/blob/master/src/html5shiv.js` is an html file and will break the site for people that are on IE8 or below.

**Comment by forki** [comment]
so what do we do?

**Comment by nickbabcock** [comment]
@DmitriyVlasov, did you want take my suggestion or use an alternative?

**Comment by sergey-tihon** [comment]
I think that would be better to use [CDN recommend by Bootstrap](http://getbootstrap.com/getting-started/#template)
https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js

**Comment by nickbabcock** [comment]
@sergey-tihon, fixed in #190

**Pull request closed without merging**
