### PR TITLE
Updates dotnet fake to fake

### PR DESCRIPTION
**Pull request by jeremyabbott**
Also updates build.sh to call `fake run init.fsx`

Co-authored-by: Jeff Boek <jeff@jeffboek.com>

### CODE REVIEW

**Comment by jeremyabbott** [comment]
@jackfoxy submitted for your approval. cc: @boek

**Comment by jeremyabbott** [comment]
@jackfoxy this was tested on a Mac with the latest version of the fake global tools installed.

**Comment by jeremyabbott** [comment]
Should resolve #332

**Comment by jackfoxy** [comment]
Did you determine if the documentation needs updating to include installing fake global tools, or does paket magically handle that?

**Pull request merged**
