### PR TITLE
docs as GitHub Pages source folder

### PR DESCRIPTION
**Pull request by jackfoxy**
simpler model to publish project gh pages

### CODE REVIEW

**Comment by jackfoxy** [comment]
This PR related to issue https://github.com/fsprojects/ProjectScaffold/issues/201#issuecomment-258626595 If there is interest in carrying this forward, I can resolve the merge conflict. This is implemented as a hard cut-over to the simpler model of publishing docs on Github. In other words the gh-pages option would not be available.

**Comment by dsyme** [comment]
@jackfoxy @rmunn @pblasucci Do we want to take this forward?

**Comment by pblasucci** [comment]
I'm fine with this change. A surprisingly high number of folks never even use the documentation features in ProjectScaffold. Maybe a simpler tooling story will change that?

👍

**Comment by pblasucci** [comment]
One question, though: how does this relate to #279?

**Comment by jackfoxy** [comment]
@pblasucci  it's been a while. Looks like #279 changes the documentation. I'll get to this on the weekend and make sure both PRs are up to date with current master and still does what I think it does. I've been maintaining my own fork lately.

**Comment by jackfoxy** [comment]
BTW, on the other forks I've added tips on retrofitting Project Scaffold to already existing git projects, should I add that to the getting started documentation?

**Comment by pblasucci** [comment]
Whoops! Didn't mean to close. Hit the wrong button (stupid tiny phone keyboard). Anyway...

Thanks @jackfoxy. This is good stuff. And, yes please! If you could include the additional docs, that'd be awesome.

**Comment by rmunn** [comment]
:+1: from me. I'm not 100% happy with `docsraw` as the name, but the only alternatives I've come up with so far are `docssrc`, or possibly `docsrc` since the two consecutive `s` characters in `docssrc` seem strange. But both of those could lead to confusion with `src`, so although I'm not totally happy with the name `docsraw`, it's still better than anything I've come up with so far.

**Comment by dsyme** [comment]
``docsraw`` isn't great.  I suggest ``src/docs``?  Not ideal but not too bad

**Comment by jackfoxy** [comment]
Now it's coming back to me #279 is a PR on gh-pages. Working on ````src/docs````.

**Comment by jackfoxy** [comment]
@pblasucci  this PR is ready. ````gh-pages```` PR #279 also ready. (Maybe don't need a separate PR?) I added tips on migrating an existing project to ````README.md````. @dsyme  src/docs caused problems in ````init.fsx````, so I renamed the ````docsraw```` folder ````docsrc````.

**Pull request merged**
