### PR TITLE
use FAKE for documentation generation.

### PR DESCRIPTION
**Pull request by matthid**
Should fix https://github.com/mathnet/mathnet-numerics/issues/346, https://github.com/tpetricek/FSharp.Formatting/issues/328, https://github.com/tpetricek/FSharp.Formatting/issues/356 and https://github.com/fsprojects/ProjectScaffold/issues/210.

### CODE REVIEW

**Comment by matthid** [comment]
As a side effect we now don't need to have F# installed for the documentation generation and it should work as long as you use compatible FSF/FAKE versions (if they are not compatible you are already doomed for various other reasons https://github.com/tpetricek/FSharp.Formatting/issues/337).

**Comment by 7sharp9** [comment]
This seems to work from initial setup :-)

**Comment by cdrnet** [comment]
Thanks!

**Comment by tpetricek** [comment]
Sounds good, thanks @matthid for looking into this! Looks like this works for @cdrnet and @7sharp9 so I'm going to merge the PR!

**Pull request merged**
