### PR TITLE
The task "Rebuild" was replaced by "Build" task in target "Build"

### LINKED ISSUE #258: Why used Rebuild task instead Build in build.template file?
Hi, all!

Maybe answer will be obvious, but I can't understand why in the target `Build` in the file `build.template`, used task `Rebuild` instead `Build` for build solution (project).

As far as I know, only `Build` task allows incremental build that gives us the big boost in the build speed.

### PR DESCRIPTION
**Pull request by Chicker**
Also, the target "Rebuild" with the "Rebuild" task was added in "build.template" file.

This commit fixes #258

### CODE REVIEW

**Comment by pblasucci** [comment]
@forki Personally, it seems a bit "off" to me. I understand wanting to speed up incremental builds. But I strongly believe the `Release` target should work off of a fully clean rebuild. Also, I've never found the perf difference between "Build" and "Rebuild" to be worth the headache of having separate commands. What are your thoughts?

**Comment by forki** [comment]
Yeah I think we should not merge it. I mean it's a good idea for some use
cases but I think we should play it safe for the scheduling process.

**Comment by pblasucci** [comment]
Agreed. Also, when you consider the way certain things (in VS/MSBuild) get cached, this doesn't feel like a "safe default".

Closing as "too specialized".

**Comment by forki** [comment]
@Chicker we still really appreciate that you took the time and effort. It's not a bad idea. I hope you can understand the reasoning.

**Pull request closed without merging**
